package com.optus.supercal.entity;
// Generated Jul 15, 2011 10:09:14 PM by Hibernate Tools 3.2.4.GA

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.validation.constraints.NotNull;

import org.hibernate.validator.constraints.Length;

/**
 * AuditRecord generated by hbm2java
 */
@Entity
@Table(name = "AUDIT_RECORD", catalog = "supercal")
public class AuditRecord implements java.io.Serializable {

	private static final long serialVersionUID = -4812215086529405310L;
	private Integer id;
	private String userName;
	private String auditMessage;
	private Date auditDate;

	public AuditRecord() {
	}

	public AuditRecord(String userName, String auditMessage, Date auditDate) {
		this.userName = userName;
		this.auditMessage = auditMessage;
		this.auditDate = auditDate;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "ID", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "USER_NAME", nullable = false, length = 45)
	@NotNull
	@Length(max = 45)
	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	@Column(name = "AUDIT_MESSAGE", nullable = false, length = 65535)
	@NotNull
	@Length(max = 65535)
	public String getAuditMessage() {
		return this.auditMessage;
	}

	public void setAuditMessage(String auditMessage) {
		this.auditMessage = auditMessage;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "AUDIT_DATE", nullable = false, length = 19)
	@NotNull
	public Date getAuditDate() {
		return this.auditDate;
	}

	public void setAuditDate(Date auditDate) {
		this.auditDate = auditDate;
	}

}
