package com.optus.supercal.entity;
// Generated Jul 15, 2011 10:09:14 PM by Hibernate Tools 3.2.4.GA

import static javax.persistence.GenerationType.IDENTITY;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.OrderBy;
import javax.persistence.Table;
import javax.validation.constraints.NotNull;

import org.codehaus.jackson.annotate.JsonIgnore;
import org.hibernate.annotations.Cascade;
import org.hibernate.validator.constraints.Length;


/**
 * BoltOnFamily generated by hbm2java
 */
@Entity
@Table(name = "BOLT_ON_FAMILY", catalog = "supercal")
public class BoltOnFamily implements java.io.Serializable {

	private static final long serialVersionUID = -1915888383748616936L;
	private Integer id;
	private String boltOnFamilyName;
	private String status;
	private Set<RatePlanFamilyBoltOnFamilyConfig> ratePlanFamilyBoltOnFamilyConfigs
		= new HashSet<RatePlanFamilyBoltOnFamilyConfig>(0);
	private Set<BoltOnFamilyFieldConfig> boltOnFamilyFieldConfigs
		= new HashSet<BoltOnFamilyFieldConfig>(0);

	public BoltOnFamily() {
	}

	public BoltOnFamily(String status) {
		this.status = status;
	}
	public BoltOnFamily(
			String boltOnFamilyName,
			String status,
			Set<RatePlanFamilyBoltOnFamilyConfig> ratePlanFamilyBoltOnFamilyConfigs,
			Set<BoltOnFamilyFieldConfig> boltOnFamilyFieldConfigs) {
		this.boltOnFamilyName = boltOnFamilyName;
		this.status = status;
		this.ratePlanFamilyBoltOnFamilyConfigs = ratePlanFamilyBoltOnFamilyConfigs;
		this.boltOnFamilyFieldConfigs = boltOnFamilyFieldConfigs;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "ID", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "BOLT_ON_FAMILY_NAME", length = 150)
	@Length(max = 150)
	public String getBoltOnFamilyName() {
		return this.boltOnFamilyName;
	}

	public void setBoltOnFamilyName(String boltOnFamilyName) {
		this.boltOnFamilyName = boltOnFamilyName;
	}

	@Column(name = "STATUS", nullable = false, length = 8)
	@NotNull
	@Length(max = 8)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	@JsonIgnore
	@OneToMany(fetch = FetchType.EAGER, cascade=CascadeType.ALL,
			mappedBy = "boltOnFamily")
	@OrderBy("sequenceNo asc")
	public Set<RatePlanFamilyBoltOnFamilyConfig> getRatePlanFamilyBoltOnFamilyConfigs() {
		return this.ratePlanFamilyBoltOnFamilyConfigs;
	}

	public void setRatePlanFamilyBoltOnFamilyConfigs(
			Set<RatePlanFamilyBoltOnFamilyConfig> ratePlanFamilyBoltOnFamilyConfigs) {
		this.ratePlanFamilyBoltOnFamilyConfigs = ratePlanFamilyBoltOnFamilyConfigs;
	}

	@JsonIgnore
	@OneToMany(fetch = FetchType.EAGER, cascade=CascadeType.ALL,
			mappedBy = "boltOnFamily", orphanRemoval=true)
	/*@Cascade(value={org.hibernate.annotations.CascadeType.ALL, 
			org.hibernate.annotations.CascadeType.DELETE_ORPHAN})*/	
	@OrderBy("sequenceNo asc")
	public Set<BoltOnFamilyFieldConfig> getBoltOnFamilyFieldConfigs() {
		return this.boltOnFamilyFieldConfigs;
	}

	public void setBoltOnFamilyFieldConfigs(
			Set<BoltOnFamilyFieldConfig> boltOnFamilyFieldConfigs) {
		this.boltOnFamilyFieldConfigs = boltOnFamilyFieldConfigs;
	}

}
