package com.optus.supercal.entity;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.validation.constraints.NotNull;

import org.codehaus.jackson.annotate.JsonIgnore;
import org.hibernate.validator.constraints.Length;

/**
 * BoltOnFieldValue generated by hbm2java
 */
@Entity
@Table(name = "BOLT_ON_FIELD_VALUE", catalog = "supercal")
public class BoltOnFieldValue implements java.io.Serializable {

	private static final long serialVersionUID = 3416248125539169598L;
	private Integer id;
	private BoltOn boltOn;
	private BoltOnFamilyFieldConfig boltOnFamilyFieldConfig;
	private String boltOnFieldValue;

	public BoltOnFieldValue() {
	}

	public BoltOnFieldValue(BoltOn boltOn,
			BoltOnFamilyFieldConfig boltOnFamilyFieldConfig,
			String boltOnFieldValue) {
		this.boltOn = boltOn;
		this.boltOnFamilyFieldConfig = boltOnFamilyFieldConfig;
		this.boltOnFieldValue = boltOnFieldValue;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "ID", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@JsonIgnore
	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "BOLT_ON_ID", nullable = false)
	@NotNull
	public BoltOn getBoltOn() {
		return this.boltOn;
	}

	public void setBoltOn(BoltOn boltOn) {
		this.boltOn = boltOn;
	}

	@JsonIgnore
	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "BOLT_ON_FAMILY_FIELD_CONFIG_ID", nullable = false)
	@NotNull
	public BoltOnFamilyFieldConfig getBoltOnFamilyFieldConfig() {
		return this.boltOnFamilyFieldConfig;
	}

	public void setBoltOnFamilyFieldConfig(
			BoltOnFamilyFieldConfig boltOnFamilyFieldConfig) {
		this.boltOnFamilyFieldConfig = boltOnFamilyFieldConfig;
	}

	@Column(name = "BOLT_ON_FIELD_VALUE", nullable = false, length = 2000)
	@NotNull
	@Length(max = 2000)
	public String getBoltOnFieldValue() {
		return this.boltOnFieldValue;
	}

	public void setBoltOnFieldValue(String boltOnFieldValue) {
		this.boltOnFieldValue = boltOnFieldValue;
	}

}
