package com.optus.supercal.entity;
// Generated Jul 15, 2011 10:09:14 PM by Hibernate Tools 3.2.4.GA

import static javax.persistence.GenerationType.IDENTITY;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Transient;
import javax.validation.constraints.NotNull;

import org.codehaus.jackson.annotate.JsonIgnore;
import org.hibernate.validator.constraints.Length;

/**
 * BoltOn generated by hbm2java
 */
@Entity
@Table(name = "BOLT_ON", catalog = "supercal")
public class BoltOn implements java.io.Serializable {

	private static final long serialVersionUID = 7123042478855006310L;
	private static final String CLONE = " Copy";
	private Integer id;
	private String boltOnName;
	private String status;
	private Set<BoltOnFieldValue> boltOnFieldValues
		= new HashSet<BoltOnFieldValue>(0);

	public BoltOn() {
	}

	public BoltOn(String boltOnName, String status) {
		this.boltOnName = boltOnName;
		this.status = status;
	}
	
	public BoltOn(String boltOnName, String status,
			Set<BoltOnFieldValue> boltOnFieldValues) {
		this.boltOnName = boltOnName;
		this.status = status;
		this.boltOnFieldValues = boltOnFieldValues;
	}

	public BoltOn(BoltOn masterBolton) {
		this.boltOnName = masterBolton.boltOnName + CLONE;
		this.status = masterBolton.status;
		for (BoltOnFieldValue boltOnFieldValue : 
			masterBolton.getBoltOnFieldValues()) {
			BoltOnFieldValue fieldValue = new BoltOnFieldValue(this,
					boltOnFieldValue.getBoltOnFamilyFieldConfig(), 
					boltOnFieldValue.getBoltOnFieldValue());
			this.getBoltOnFieldValues().add(fieldValue);
		}
	}
	
	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "ID", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "BOLT_ON_NAME", nullable = false, length = 150)
	@NotNull
	@Length(max = 150)
	public String getBoltOnName() {
		return this.boltOnName;
	}

	public void setBoltOnName(String boltOnName) {
		this.boltOnName = boltOnName;
	}

	@Column(name = "STATUS", nullable = false, length = 8)
	@NotNull
	@Length(max = 8)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	@JsonIgnore
	@OneToMany(fetch = FetchType.EAGER, cascade=CascadeType.ALL,
			mappedBy = "boltOn")
	public Set<BoltOnFieldValue> getBoltOnFieldValues() {
		return this.boltOnFieldValues;
	}

	public void setBoltOnFieldValues(Set<BoltOnFieldValue> boltOnFieldValues) {
		this.boltOnFieldValues = boltOnFieldValues;
	}

	@Transient
	public BoltOnFamily getBoltOnFamily() {
		if (boltOnFieldValues.isEmpty()) {
			return null;
		} else {
			return boltOnFieldValues.iterator().next()
					.getBoltOnFamilyFieldConfig().getBoltOnFamily();
		}
	}
}
