package com.optus.supercal.entity;
// Generated 16/08/2011 11:37:55 AM by Hibernate Tools 3.2.4.GA

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.validation.constraints.NotNull;

import org.hibernate.annotations.Cascade;
import org.hibernate.validator.constraints.Length;


/**
 * EmailBoltOnAddition generated by hbm2java
 */
@Entity
@Table(name = "EMAIL_BOLT_ON_ADDITION", catalog = "supercal")
public class EmailBoltOnAddition implements java.io.Serializable {

	private static final long serialVersionUID = -5021983350543665043L;
	private Integer id;
	private String emailTemplate;
	private String emailAddress;
	private String serviceNo;
	private String customerTitle;
	private String customerFirstName;
	private String customerSurname;
	private String accountNo;
	private Date emailDateTime;
	private String emailMessage;
	private Set<BoltOnAddition> boltOnAdditions
		= new HashSet<BoltOnAddition>(0);
	private byte[] topBanner;
	private byte[] bottomBanner;
	private String sendStatus;
	
	public EmailBoltOnAddition() {
	}

	public EmailBoltOnAddition(String emailTemplate, String emailAddress,
			String serviceNo, String customerTitle, String customerFirstName,
			String customerSurname, String accountNo, Date emailDateTime,
			String emailMessage) {
		this.emailTemplate = emailTemplate;
		this.emailAddress = emailAddress;
		this.serviceNo = serviceNo;
		this.customerTitle = customerTitle;
		this.customerFirstName = customerFirstName;
		this.customerSurname = customerSurname;
		this.accountNo = accountNo;
		this.emailDateTime = emailDateTime;
		this.emailMessage = emailMessage;
	}

	public EmailBoltOnAddition(EmailBoltOnAddition emailBoltOnAddition) {
		this.emailTemplate = emailBoltOnAddition.emailTemplate;
		this.emailAddress = emailBoltOnAddition.emailAddress;
		this.serviceNo = emailBoltOnAddition.serviceNo;
		this.customerTitle = emailBoltOnAddition.customerTitle;
		this.customerFirstName = emailBoltOnAddition.customerFirstName;
		this.customerSurname = emailBoltOnAddition.customerSurname;
		this.accountNo = emailBoltOnAddition.accountNo;
		this.emailDateTime = emailBoltOnAddition.emailDateTime;
		this.emailMessage = emailBoltOnAddition.emailMessage;
		this.sendStatus = emailBoltOnAddition.sendStatus;
		this.topBanner = emailBoltOnAddition.topBanner;
		this.bottomBanner = emailBoltOnAddition.bottomBanner;
	}
	
	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "ID", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "EMAIL_TEMPLATE", nullable = false, length = 150)
	@NotNull
	@Length(max = 150)
	public String getEmailTemplate() {
		return this.emailTemplate;
	}

	public void setEmailTemplate(String emailTemplate) {
		this.emailTemplate = emailTemplate;
	}

	@Column(name = "EMAIL_ADDRESS", nullable = false, length = 150)
	@NotNull
	@Length(max = 150)
	public String getEmailAddress() {
		return this.emailAddress;
	}

	public void setEmailAddress(String emailAddress) {
		this.emailAddress = emailAddress;
	}

	@Column(name = "SERVICE_NO", nullable = false, length = 45)
	@NotNull
	@Length(max = 45)
	public String getServiceNo() {
		return this.serviceNo;
	}

	public void setServiceNo(String serviceNo) {
		this.serviceNo = serviceNo;
	}

	@Column(name = "CUSTOMER_TITLE", nullable = false, length = 15)
	@NotNull
	@Length(max = 15)
	public String getCustomerTitle() {
		return this.customerTitle;
	}

	public void setCustomerTitle(String customerTitle) {
		this.customerTitle = customerTitle;
	}

	@Column(name = "CUSTOMER_FIRST_NAME", nullable = false, length = 250)
	@NotNull
	@Length(max = 250)
	public String getCustomerFirstName() {
		return this.customerFirstName;
	}

	public void setCustomerFirstName(String customerFirstName) {
		this.customerFirstName = customerFirstName;
	}

	@Column(name = "CUSTOMER_SURNAME", nullable = false, length = 250)
	@NotNull
	@Length(max = 250)
	public String getCustomerSurname() {
		return this.customerSurname;
	}

	public void setCustomerSurname(String customerSurname) {
		this.customerSurname = customerSurname;
	}

	@Column(name = "ACCOUNT_NO", length = 45)
	@Length(max = 45)
	public String getAccountNo() {
		return this.accountNo;
	}

	public void setAccountNo(String accountNo) {
		this.accountNo = accountNo;
	}
	
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "EMAIL_DATE_TIME", nullable = false, length = 19)
	@NotNull
	public Date getEmailDateTime() {
		return this.emailDateTime;
	}

	public void setEmailDateTime(Date emailDateTime) {
		this.emailDateTime = emailDateTime;
	}

	@Column(name = "EMAIL_MESSAGE", nullable = false, length = 65535)
	@NotNull
	@Length(max = 65535)
	public String getEmailMessage() {
		return this.emailMessage;
	}

	public void setEmailMessage(String emailMessage) {
		this.emailMessage = emailMessage;
	}
	
	@OneToMany(fetch = FetchType.LAZY, cascade=CascadeType.ALL, 
			mappedBy = "emailBoltOnAddition")
	@Cascade(value={org.hibernate.annotations.CascadeType.ALL, 
			org.hibernate.annotations.CascadeType.DELETE_ORPHAN})
	public Set<BoltOnAddition> getBoltOnAdditions() {
		return this.boltOnAdditions;
	}

	public void setBoltOnAdditions(Set<BoltOnAddition> boltOnAdditions) {
		this.boltOnAdditions = boltOnAdditions;
	}
	
	@Column(name = "TOP_BANNER")
	public byte[] getTopBanner() {
		return this.topBanner;
	}

	public void setTopBanner(byte[] topBanner) {
		this.topBanner = topBanner;
	}

	@Column(name = "BOTTOM_BANNER")
	public byte[] getBottomBanner() {
		return this.bottomBanner;
	}

	public void setBottomBanner(byte[] bottomBanner) {
		this.bottomBanner = bottomBanner;
	}

	@Column(name = "SEND_STATUS", length = 15)
	@Length(max = 15)
	public String getSendStatus() {
		return this.sendStatus;
	}

	public void setSendStatus(String sendStatus) {
		this.sendStatus = sendStatus;
	}	
}
