package com.optus.supercal.entity;
// Generated 15/08/2011 11:59:10 AM by Hibernate Tools 3.2.4.GA

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.validation.constraints.NotNull;

import org.codehaus.jackson.annotate.JsonIgnore;
import org.hibernate.validator.constraints.Length;


/**
 * EmailTemplateBoltOnFieldConfig generated by hbm2java
 */
@Entity
@Table(name = "EMAIL_TEMPLATE_BOLT_ON_FIELD_CONFIG", catalog = "supercal")
public class EmailTemplateBoltOnFieldConfig implements java.io.Serializable,
	Comparable<EmailTemplateBoltOnFieldConfig> {

	private static final long serialVersionUID = -7144481631287662550L;
	private Integer id;
	private BoltOnField boltOnField;
	private EmailTemplate emailTemplate;
	private String fieldDisplayFormat;
	private int sequenceNo;

	public EmailTemplateBoltOnFieldConfig() {
	}

	public EmailTemplateBoltOnFieldConfig(BoltOnField boltOnField,
			EmailTemplate emailTemplate, String fieldDisplayFormat,
			int sequenceNo) {
		this.boltOnField = boltOnField;
		this.emailTemplate = emailTemplate;
		this.fieldDisplayFormat = fieldDisplayFormat;
		this.sequenceNo = sequenceNo;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "ID", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@JsonIgnore
	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "BOLT_ON_FIELD_ID", nullable = false)
	@NotNull
	public BoltOnField getBoltOnField() {
		return this.boltOnField;
	}

	public void setBoltOnField(BoltOnField boltOnField) {
		this.boltOnField = boltOnField;
	}

	@JsonIgnore
	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "EMAIL_TEMPLATE_ID", nullable = false)
	@NotNull
	public EmailTemplate getEmailTemplate() {
		return this.emailTemplate;
	}

	public void setEmailTemplate(EmailTemplate emailTemplate) {
		this.emailTemplate = emailTemplate;
	}

	@Column(name = "FIELD_DISPLAY_FORMAT", nullable = false, length = 2)
	@NotNull
	@Length(max = 2)
	public String getFieldDisplayFormat() {
		return this.fieldDisplayFormat;
	}

	public void setFieldDisplayFormat(String fieldDisplayFormat) {
		this.fieldDisplayFormat = fieldDisplayFormat;
	}

	@Column(name = "SEQUENCE_NO", nullable = false)
	public int getSequenceNo() {
		return this.sequenceNo;
	}

	public void setSequenceNo(int sequenceNo) {
		this.sequenceNo = sequenceNo;
	}

	@Override
	public int compareTo(EmailTemplateBoltOnFieldConfig o) {
		return this.getSequenceNo()	- o.getSequenceNo();
	}

}
