package com.optus.supercal.entity;
// Generated 16/08/2011 11:37:55 AM by Hibernate Tools 3.2.4.GA

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.validation.constraints.NotNull;

import org.hibernate.validator.constraints.Length;

/**
 * EmailRatePlanChange generated by hbm2java
 */
@Entity
@Table(name = "EMAIL_RATE_PLAN_CHANGE", catalog = "supercal")
public class EmailRatePlanChange implements java.io.Serializable {

	private static final long serialVersionUID = -1124489509906888444L;
	private Integer id;
	private String emailTemplate;
	private String emailAddress;
	private String serviceNo;
	private String customerTitle;
	private String customerFirstName;
	private String customerSurname;
	private String accountNo;
	private int oldRatePlanId;
	private int newRatePlanId;
	private double ratePlanChangeFee;
	private Date emailDateTime;
	private String emailMessage;
	private String message;
	private String sendStatus;
	private byte[] topBanner;
	private byte[] bottomBanner;
	
	public EmailRatePlanChange() {
	}

	public EmailRatePlanChange(String emailTemplate, String emailAddress,
			String serviceNo, String customerTitle, String customerFirstName,
			String customerSurname, String accountNo, int oldRatePlanId,
			int newRatePlanId, double ratePlanChangeFee, Date emailDateTime,
			String emailMessage) {
		this.emailTemplate = emailTemplate;
		this.emailAddress = emailAddress;
		this.serviceNo = serviceNo;
		this.customerTitle = customerTitle;
		this.customerFirstName = customerFirstName;
		this.customerSurname = customerSurname;
		this.accountNo = accountNo;
		this.oldRatePlanId = oldRatePlanId;
		this.newRatePlanId = newRatePlanId;
		this.ratePlanChangeFee = ratePlanChangeFee;
		this.emailDateTime = emailDateTime;
		this.emailMessage = emailMessage;
	}

	public EmailRatePlanChange(EmailRatePlanChange emailRatePlanChange) {
		this.emailTemplate = emailRatePlanChange.emailTemplate;
		this.emailAddress = emailRatePlanChange.emailAddress;
		this.serviceNo = emailRatePlanChange.serviceNo;
		this.customerTitle = emailRatePlanChange.customerTitle;
		this.customerFirstName = emailRatePlanChange.customerFirstName;
		this.customerSurname = emailRatePlanChange.customerSurname;
		this.accountNo = emailRatePlanChange.accountNo;
		this.oldRatePlanId = emailRatePlanChange.oldRatePlanId;
		this.newRatePlanId = emailRatePlanChange.newRatePlanId;
		this.ratePlanChangeFee = emailRatePlanChange.ratePlanChangeFee;
		this.emailDateTime = emailRatePlanChange.emailDateTime;
		this.sendStatus = emailRatePlanChange.sendStatus;
		this.emailMessage = emailRatePlanChange.emailMessage;
		this.topBanner = emailRatePlanChange.topBanner;
		this.bottomBanner = emailRatePlanChange.bottomBanner;
	}
	
	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "ID", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "EMAIL_TEMPLATE", nullable = false, length = 150)
	@NotNull
	@Length(max = 150)
	public String getEmailTemplate() {
		return this.emailTemplate;
	}

	public void setEmailTemplate(String emailTemplate) {
		this.emailTemplate = emailTemplate;
	}

	@Column(name = "EMAIL_ADDRESS", nullable = false, length = 150)
	@NotNull
	@Length(max = 150)
	public String getEmailAddress() {
		return this.emailAddress;
	}

	public void setEmailAddress(String emailAddress) {
		this.emailAddress = emailAddress;
	}

	@Column(name = "SERVICE_NO", nullable = false, length = 45)
	@NotNull
	@Length(max = 45)
	public String getServiceNo() {
		return this.serviceNo;
	}

	public void setServiceNo(String serviceNo) {
		this.serviceNo = serviceNo;
	}

	@Column(name = "CUSTOMER_TITLE", nullable = false, length = 15)
	@NotNull
	@Length(max = 15)
	public String getCustomerTitle() {
		return this.customerTitle;
	}

	public void setCustomerTitle(String customerTitle) {
		this.customerTitle = customerTitle;
	}

	@Column(name = "CUSTOMER_FIRST_NAME", nullable = false, length = 250)
	@NotNull
	@Length(max = 250)
	public String getCustomerFirstName() {
		return this.customerFirstName;
	}

	public void setCustomerFirstName(String customerFirstName) {
		this.customerFirstName = customerFirstName;
	}

	@Column(name = "CUSTOMER_SURNAME", nullable = false, length = 250)
	@NotNull
	@Length(max = 250)
	public String getCustomerSurname() {
		return this.customerSurname;
	}

	public void setCustomerSurname(String customerSurname) {
		this.customerSurname = customerSurname;
	}
	
	@Column(name = "ACCOUNT_NO", length = 45)
	@Length(max = 45)
	public String getAccountNo() {
		return this.accountNo;
	}

	public void setAccountNo(String accountNo) {
		this.accountNo = accountNo;
	}
	
	@Column(name = "OLD_RATE_PLAN_ID", nullable = false)
	public int getOldRatePlanId() {
		return this.oldRatePlanId;
	}

	public void setOldRatePlanId(int oldRatePlanId) {
		this.oldRatePlanId = oldRatePlanId;
	}

	@Column(name = "NEW_RATE_PLAN_ID", nullable = false)
	public int getNewRatePlanId() {
		return this.newRatePlanId;
	}

	public void setNewRatePlanId(int newRatePlanId) {
		this.newRatePlanId = newRatePlanId;
	}

	@Column(name = "RATE_PLAN_CHANGE_FEE", nullable = false, precision = 6, scale = 2)
	public double getRatePlanChangeFee() {
		return this.ratePlanChangeFee;
	}

	public void setRatePlanChangeFee(double ratePlanChangeFee) {
		this.ratePlanChangeFee = ratePlanChangeFee;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "EMAIL_DATE_TIME", nullable = false, length = 19)
	@NotNull
	public Date getEmailDateTime() {
		return this.emailDateTime;
	}

	public void setEmailDateTime(Date emailDateTime) {
		this.emailDateTime = emailDateTime;
	}

	@Column(name = "EMAIL_MESSAGE", nullable = false, length = 65535)
	@NotNull
	@Length(max = 65535)
	public String getEmailMessage() {
		return this.emailMessage;
	}

	public void setEmailMessage(String emailMessage) {
		this.emailMessage = emailMessage;
	}
	
	@Column(name = "SEND_STATUS")
	public String getSendStatus() {
		return sendStatus;
	}

	public void setSendStatus(String sendStatus) {
		this.sendStatus = sendStatus;
	}

	@Column(name = "MESSAGE", length = 65535)
	@Length(max = 65535)
	public String getMessage() {
		return this.message;
	}

	public void setMessage(String message) {
		this.message = message;
	}

	@Column(name = "TOP_BANNER")
	public byte[] getTopBanner() {
		return this.topBanner;
	}

	public void setTopBanner(byte[] topBanner) {
		this.topBanner = topBanner;
	}

	@Column(name = "BOTTOM_BANNER")
	public byte[] getBottomBanner() {
		return this.bottomBanner;
	}

	public void setBottomBanner(byte[] bottomBanner) {
		this.bottomBanner = bottomBanner;
	}
}
