package com.optus.supercal.entity;
// Generated Jul 15, 2011 10:09:14 PM by Hibernate Tools 3.2.4.GA

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.validation.constraints.NotNull;

import org.codehaus.jackson.annotate.JsonIgnore;


/**
 * EmailTemplateOpomFieldConfig generated by hbm2java
 */
@Entity
@Table(name = "EMAIL_TEMPLATE_OPOM_FIELD_CONFIG", catalog = "supercal")
public class EmailTemplateOpomFieldConfig implements java.io.Serializable,
	Comparable<EmailTemplateOpomFieldConfig> {

	private static final long serialVersionUID = -4229811676547703094L;
	private Integer id;
	private OpomEmailField opomEmailField;
	private EmailTemplate emailTemplate;
	private String fieldDisplayFormat = "SF";
	private int sequenceNo;

	public EmailTemplateOpomFieldConfig() {
	}

	public EmailTemplateOpomFieldConfig(OpomEmailField opomEmailField, EmailTemplate
			emailTemplate, String fieldDisplayFormat, int sequenceNo) {
		this.opomEmailField = opomEmailField;
		this.emailTemplate = emailTemplate;
		this.fieldDisplayFormat = fieldDisplayFormat;
		this.sequenceNo = sequenceNo;
	}

	public EmailTemplateOpomFieldConfig(OpomEmailField opomEmailField,
			EmailTemplate emailTemplate, int sequenceNo) {
		this.opomEmailField = opomEmailField;
		this.emailTemplate = emailTemplate;
		this.sequenceNo = sequenceNo;
	}
	
	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "ID", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@JsonIgnore
	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "OPOM_EMAIL_FIELD_ID", nullable = false)
	@NotNull
	public OpomEmailField getOpomEmailField() {
		return this.opomEmailField;
	}

	public void setOpomEmailField(OpomEmailField opomEmailField) {
		this.opomEmailField = opomEmailField;
	}

	@JsonIgnore
	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "EMAIL_TEMPLATE_ID", nullable = false)
	@NotNull
	public EmailTemplate getEmailTemplate() {
		return this.emailTemplate;
	}

	public void setEmailTemplate(EmailTemplate emailTemplate) {
		this.emailTemplate = emailTemplate;
	}
	
	@Column(name = "FIELD_DISPLAY_FORMAT", nullable = false)
	public String getFieldDisplayFormat() {
		return fieldDisplayFormat;
	}

	public void setFieldDisplayFormat(String fieldDisplayFormat) {
		this.fieldDisplayFormat = fieldDisplayFormat;
	}

	@Column(name = "SEQUENCE_NO", nullable = false)
	public int getSequenceNo() {
		return this.sequenceNo;
	}

	public void setSequenceNo(int sequenceNo) {
		this.sequenceNo = sequenceNo;
	}
	
	@Override
	public int compareTo(EmailTemplateOpomFieldConfig o) {
		return this.getSequenceNo()	- o.getSequenceNo();
	}
}
