package com.optus.supercal.entity;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.validation.constraints.NotNull;

import org.codehaus.jackson.annotate.JsonIgnore;
import org.hibernate.validator.constraints.Length;


/**
 * EmailTemplateRatePlanFieldConfig generated by hbm2java
 */
@Entity
@Table(name = "EMAIL_TEMPLATE_RATE_PLAN_FIELD_CONFIG", catalog = "supercal")
public class EmailTemplateRatePlanFieldConfig implements java.io.Serializable,
	Comparable<EmailTemplateRatePlanFieldConfig> {

	private static final long serialVersionUID = -4038894048980813497L;
	private Integer id;
	private RatePlanField ratePlanField;
	private EmailTemplate emailTemplate;
	private String fieldDisplayFormat;
	private int sequenceNo;

	public EmailTemplateRatePlanFieldConfig() {
	}

	public EmailTemplateRatePlanFieldConfig(RatePlanField ratePlanField,
			EmailTemplate emailTemplate, String fieldDisplayFormat,
			int sequenceNo) {
		this.ratePlanField = ratePlanField;
		this.emailTemplate = emailTemplate;
		this.fieldDisplayFormat = fieldDisplayFormat;
		this.sequenceNo = sequenceNo;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "ID", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@JsonIgnore
	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "RATE_PLAN_FIELD_ID", nullable = false)
	@NotNull
	public RatePlanField getRatePlanField() {
		return this.ratePlanField;
	}

	public void setRatePlanField(RatePlanField ratePlanField) {
		this.ratePlanField = ratePlanField;
	}

	@JsonIgnore
	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "EMAIL_TEMPLATE_ID", nullable = false)
	@NotNull
	public EmailTemplate getEmailTemplate() {
		return this.emailTemplate;
	}

	public void setEmailTemplate(EmailTemplate emailTemplate) {
		this.emailTemplate = emailTemplate;
	}

	@Column(name = "FIELD_DISPLAY_FORMAT", nullable = false, length = 2)
	@NotNull
	@Length(max = 2)
	public String getFieldDisplayFormat() {
		return this.fieldDisplayFormat;
	}

	public void setFieldDisplayFormat(String fieldDisplayFormat) {
		this.fieldDisplayFormat = fieldDisplayFormat;
	}

	@Column(name = "SEQUENCE_NO", nullable = false)
	public int getSequenceNo() {
		return this.sequenceNo;
	}

	public void setSequenceNo(int sequenceNo) {
		this.sequenceNo = sequenceNo;
	}

	@Override
	public int compareTo(EmailTemplateRatePlanFieldConfig o) {
		return this.getSequenceNo()	- o.getSequenceNo();
	}

}
