package com.optus.supercal.entity;
// Generated Jul 15, 2011 10:09:14 PM by Hibernate Tools 3.2.4.GA

import static javax.persistence.GenerationType.IDENTITY;

import java.lang.reflect.Field;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Transient;

import org.hibernate.validator.constraints.Length;

/**
 * OpomData generated by hbm2java
 */
@Entity
@Table(name = "OPOM_DATA", catalog = "supercal")
public class OpomData implements java.io.Serializable {

	private static final long serialVersionUID = -243529242004345864L;

	private Integer id;
	private String cfu;
	private String srcAccountNumber;
	private String acctName;
	private String billAddress1;
	private String billAddress2;
	private String billCity;
	private String billState;
	private String billZip;
	private String salutation;
	private String firstNm;
	private String lastNm;
	private String emailAddr;
	private String svcNo;
	private String svcEffDt;
	private String contractName;
	private String contractTerm;
	private String contractEffectiveDate;
	private String contractEndDate;
	private String byoContractInd;
	private String yesThanksContractInd;
	private String ratePlanCd;
	private String ratePlanName;
	private String ratePlanEffDt;
	private String ratePlanAccessFee;
	private String prodType;
	private String reportParentDealerCode;
	private String reportParentDealerName;
	private String reportParentGroupCode;
	private String handsetManufacturer;
	private String handsetType;
	private String imei;
	private String handsetDeliveryDt;
	private String sosOrderNo;
	private String salesRepId;
	private String createdDt;
	private String totalMinCost;
	private String oneTimeCharge;
	private String gaDaInd;
	private String delAddrBuildingName;
	private String delAddrSubAddressType;
	private String delAddrSubAddressNo;
	private String delAddrStreetNo;
	private String delAddrStreetName;
	private String delAddrStreetType;
	private String delAddrCity;
	private String delAddrState;
	private String delAddrPostcode;
	private String sapDelivery;
	private String handsetSapDelivery;

	public OpomData() {
	}

	public OpomData(String cfu, String srcAccountNumber, String acctName,
			String billAddress1, String billAddress2, String billCity,
			String billState, String billZip, String salutation,
			String firstNm, String lastNm, String emailAddr, String svcNo,
			String svcEffDt, String contractName, String contractTerm,
			String contractEffectiveDate, String contractEndDate,
			String byoContractInd, String yesThanksContractInd,
			String ratePlanCd, String ratePlanName, String ratePlanEffDt,
			String ratePlanAccessFee, String prodType,
			String reportParentDealerCode, String reportParentDealerName,
			String reportParentGroupCode, String handsetManufacturer,
			String handsetType, String imei, String handsetDeliveryDt,
			String sosOrderNo, String salesRepId, String createdDt,
			String totalMinCost, String oneTimeCharge, String gaDaInd,
			String delAddrBuildingName, String delAddrSubAddressType,
			String delAddrSubAddressNo, String delAddrStreetNo,
			String delAddrStreetName, String delAddrStreetType,
			String delAddrCity, String delAddrState, String delAddrPostcode,
			String sapDelivery, String handsetSapDelivery) {
		this.cfu = cfu;
		this.srcAccountNumber = srcAccountNumber;
		this.acctName = acctName;
		this.billAddress1 = billAddress1;
		this.billAddress2 = billAddress2;
		this.billCity = billCity;
		this.billState = billState;
		this.billZip = billZip;
		this.salutation = salutation;
		this.firstNm = firstNm;
		this.lastNm = lastNm;
		this.emailAddr = emailAddr;
		this.svcNo = svcNo;
		this.svcEffDt = svcEffDt;
		this.contractName = contractName;
		this.contractTerm = contractTerm;
		this.contractEffectiveDate = contractEffectiveDate;
		this.contractEndDate = contractEndDate;
		this.byoContractInd = byoContractInd;
		this.yesThanksContractInd = yesThanksContractInd;
		this.ratePlanCd = ratePlanCd;
		this.ratePlanName = ratePlanName;
		this.ratePlanEffDt = ratePlanEffDt;
		this.ratePlanAccessFee = ratePlanAccessFee;
		this.prodType = prodType;
		this.reportParentDealerCode = reportParentDealerCode;
		this.reportParentDealerName = reportParentDealerName;
		this.reportParentGroupCode = reportParentGroupCode;
		this.handsetManufacturer = handsetManufacturer;
		this.handsetType = handsetType;
		this.imei = imei;
		this.handsetDeliveryDt = handsetDeliveryDt;
		this.sosOrderNo = sosOrderNo;
		this.salesRepId = salesRepId;
		this.createdDt = createdDt;
		this.totalMinCost = totalMinCost;
		this.oneTimeCharge = oneTimeCharge;
		this.gaDaInd = gaDaInd;
		this.delAddrBuildingName = delAddrBuildingName;
		this.delAddrSubAddressType = delAddrSubAddressType;
		this.delAddrSubAddressNo = delAddrSubAddressNo;
		this.delAddrStreetNo = delAddrStreetNo;
		this.delAddrStreetName = delAddrStreetName;
		this.delAddrStreetType = delAddrStreetType;
		this.delAddrCity = delAddrCity;
		this.delAddrState = delAddrState;
		this.delAddrPostcode = delAddrPostcode;
		this.sapDelivery = sapDelivery;
		this.handsetSapDelivery = handsetSapDelivery;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "ID", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "CFU")
	public String getCfu() {
		return this.cfu;
	}

	public void setCfu(String cfu) {
		this.cfu = cfu;
	}

	@Column(name = "SRC_ACCOUNT_NUMBER")
	public String getSrcAccountNumber() {
		return this.srcAccountNumber;
	}

	public void setSrcAccountNumber(String srcAccountNumber) {
		this.srcAccountNumber = srcAccountNumber;
	}

	@Column(name = "ACCT_NAME")
	public String getAcctName() {
		return this.acctName;
	}

	public void setAcctName(String acctName) {
		this.acctName = acctName;
	}

	@Column(name = "BILL_ADDRESS1")
	public String getBillAddress1() {
		return this.billAddress1;
	}

	public void setBillAddress1(String billAddress1) {
		this.billAddress1 = billAddress1;
	}

	@Column(name = "BILL_ADDRESS2")
	public String getBillAddress2() {
		return this.billAddress2;
	}

	public void setBillAddress2(String billAddress2) {
		this.billAddress2 = billAddress2;
	}

	@Column(name = "BILL_CITY")
	public String getBillCity() {
		return this.billCity;
	}

	public void setBillCity(String billCity) {
		this.billCity = billCity;
	}

	@Column(name = "BILL_STATE")
	public String getBillState() {
		return this.billState;
	}

	public void setBillState(String billState) {
		this.billState = billState;
	}

	@Column(name = "BILL_ZIP")
	public String getBillZip() {
		return this.billZip;
	}

	public void setBillZip(String billZip) {
		this.billZip = billZip;
	}

	@Column(name = "SALUTATION")
	public String getSalutation() {
		return this.salutation;
	}

	public void setSalutation(String salutation) {
		this.salutation = salutation;
	}

	@Column(name = "FIRST_NM")
	public String getFirstNm() {
		return this.firstNm;
	}

	public void setFirstNm(String firstNm) {
		this.firstNm = firstNm;
	}

	@Column(name = "LAST_NM")
	public String getLastNm() {
		return this.lastNm;
	}

	public void setLastNm(String lastNm) {
		this.lastNm = lastNm;
	}

	@Column(name = "EMAIL_ADDR")
	public String getEmailAddr() {
		return this.emailAddr;
	}

	public void setEmailAddr(String emailAddr) {
		this.emailAddr = emailAddr;
	}

	@Column(name = "SVC_NO")
	public String getSvcNo() {
		return this.svcNo;
	}

	public void setSvcNo(String svcNo) {
		this.svcNo = svcNo;
	}

	@Column(name = "SVC_EFF_DT")
	public String getSvcEffDt() {
		return this.svcEffDt;
	}

	public void setSvcEffDt(String svcEffDt) {
		this.svcEffDt = svcEffDt;
	}

	@Column(name = "CONTRACT_NAME")
	public String getContractName() {
		return this.contractName;
	}

	public void setContractName(String contractName) {
		this.contractName = contractName;
	}

	@Column(name = "CONTRACT_TERM")
	public String getContractTerm() {
		return this.contractTerm;
	}

	public void setContractTerm(String contractTerm) {
		this.contractTerm = contractTerm;
	}

	@Column(name = "CONTRACT_EFFECTIVE_DATE")
	public String getContractEffectiveDate() {
		return this.contractEffectiveDate;
	}

	public void setContractEffectiveDate(String contractEffectiveDate) {
		this.contractEffectiveDate = contractEffectiveDate;
	}

	@Column(name = "CONTRACT_END_DATE")
	public String getContractEndDate() {
		return this.contractEndDate;
	}

	public void setContractEndDate(String contractEndDate) {
		this.contractEndDate = contractEndDate;
	}

	@Column(name = "BYO_CONTRACT_IND")
	public String getByoContractInd() {
		return this.byoContractInd;
	}

	public void setByoContractInd(String byoContractInd) {
		this.byoContractInd = byoContractInd;
	}

	@Column(name = "YES_THANKS_CONTRACT_IND")
	public String getYesThanksContractInd() {
		return this.yesThanksContractInd;
	}

	public void setYesThanksContractInd(String yesThanksContractInd) {
		this.yesThanksContractInd = yesThanksContractInd;
	}

	@Column(name = "RATE_PLAN_CD")
	public String getRatePlanCd() {
		return this.ratePlanCd;
	}

	public void setRatePlanCd(String ratePlanCd) {
		this.ratePlanCd = ratePlanCd;
	}

	@Column(name = "RATE_PLAN_NAME")
	public String getRatePlanName() {
		return this.ratePlanName;
	}

	public void setRatePlanName(String ratePlanName) {
		this.ratePlanName = ratePlanName;
	}

	@Column(name = "RATE_PLAN_EFF_DT")
	public String getRatePlanEffDt() {
		return this.ratePlanEffDt;
	}

	public void setRatePlanEffDt(String ratePlanEffDt) {
		this.ratePlanEffDt = ratePlanEffDt;
	}

	@Column(name = "RATE_PLAN_ACCESS_FEE")
	public String getRatePlanAccessFee() {
		return this.ratePlanAccessFee;
	}

	public void setRatePlanAccessFee(String ratePlanAccessFee) {
		this.ratePlanAccessFee = ratePlanAccessFee;
	}

	@Column(name = "PROD_TYPE")
	public String getProdType() {
		return this.prodType;
	}

	public void setProdType(String prodType) {
		this.prodType = prodType;
	}

	@Column(name = "REPORT_PARENT_DEALER_CODE")
	public String getReportParentDealerCode() {
		return this.reportParentDealerCode;
	}

	public void setReportParentDealerCode(String reportParentDealerCode) {
		this.reportParentDealerCode = reportParentDealerCode;
	}

	@Column(name = "REPORT_PARENT_DEALER_NAME")
	public String getReportParentDealerName() {
		return this.reportParentDealerName;
	}

	public void setReportParentDealerName(String reportParentDealerName) {
		this.reportParentDealerName = reportParentDealerName;
	}

	@Column(name = "REPORT_PARENT_GROUP_CODE")
	public String getReportParentGroupCode() {
		return this.reportParentGroupCode;
	}

	public void setReportParentGroupCode(String reportParentGroupCode) {
		this.reportParentGroupCode = reportParentGroupCode;
	}

	@Column(name = "HANDSET_MANUFACTURER", length = 155)
	@Length(max = 155)
	public String getHandsetManufacturer() {
		return this.handsetManufacturer;
	}

	public void setHandsetManufacturer(String handsetManufacturer) {
		this.handsetManufacturer = handsetManufacturer;
	}

	@Column(name = "HANDSET_TYPE")
	public String getHandsetType() {
		return this.handsetType;
	}

	public void setHandsetType(String handsetType) {
		this.handsetType = handsetType;
	}

	@Column(name = "IMEI")
	public String getImei() {
		return this.imei;
	}

	public void setImei(String imei) {
		this.imei = imei;
	}

	@Column(name = "HANDSET_DELIVERY_DT")
	public String getHandsetDeliveryDt() {
		return this.handsetDeliveryDt;
	}

	public void setHandsetDeliveryDt(String handsetDeliveryDt) {
		this.handsetDeliveryDt = handsetDeliveryDt;
	}

	@Column(name = "SOS_ORDER_NO")
	public String getSosOrderNo() {
		return this.sosOrderNo;
	}

	public void setSosOrderNo(String sosOrderNo) {
		this.sosOrderNo = sosOrderNo;
	}

	@Column(name = "SALES_REP_ID")
	public String getSalesRepId() {
		return this.salesRepId;
	}

	public void setSalesRepId(String salesRepId) {
		this.salesRepId = salesRepId;
	}

	@Column(name = "CREATED_DT")
	public String getCreatedDt() {
		return this.createdDt;
	}

	public void setCreatedDt(String createdDt) {
		this.createdDt = createdDt;
	}

	@Column(name = "TOTAL_MIN_COST")
	public String getTotalMinCost() {
		return this.totalMinCost;
	}

	public void setTotalMinCost(String totalMinCost) {
		this.totalMinCost = totalMinCost;
	}

	@Column(name = "ONE_TIME_CHARGE")
	public String getOneTimeCharge() {
		return this.oneTimeCharge;
	}

	public void setOneTimeCharge(String oneTimeCharge) {
		this.oneTimeCharge = oneTimeCharge;
	}

	@Column(name = "GA_DA_IND")
	public String getGaDaInd() {
		return this.gaDaInd;
	}

	public void setGaDaInd(String gaDaInd) {
		this.gaDaInd = gaDaInd;
	}

	@Column(name = "DEL_ADDR_BUILDING_NAME")
	public String getDelAddrBuildingName() {
		return this.delAddrBuildingName;
	}

	public void setDelAddrBuildingName(String delAddrBuildingName) {
		this.delAddrBuildingName = delAddrBuildingName;
	}

	@Column(name = "DEL_ADDR_SUB_ADDRESS_TYPE")
	public String getDelAddrSubAddressType() {
		return this.delAddrSubAddressType;
	}

	public void setDelAddrSubAddressType(String delAddrSubAddressType) {
		this.delAddrSubAddressType = delAddrSubAddressType;
	}

	@Column(name = "DEL_ADDR_SUB_ADDRESS_NO")
	public String getDelAddrSubAddressNo() {
		return this.delAddrSubAddressNo;
	}

	public void setDelAddrSubAddressNo(String delAddrSubAddressNo) {
		this.delAddrSubAddressNo = delAddrSubAddressNo;
	}

	@Column(name = "DEL_ADDR_STREET_NO")
	public String getDelAddrStreetNo() {
		return this.delAddrStreetNo;
	}

	public void setDelAddrStreetNo(String delAddrStreetNo) {
		this.delAddrStreetNo = delAddrStreetNo;
	}

	@Column(name = "DEL_ADDR_STREET_NAME")
	public String getDelAddrStreetName() {
		return this.delAddrStreetName;
	}

	public void setDelAddrStreetName(String delAddrStreetName) {
		this.delAddrStreetName = delAddrStreetName;
	}

	@Column(name = "DEL_ADDR_STREET_TYPE")
	public String getDelAddrStreetType() {
		return this.delAddrStreetType;
	}

	public void setDelAddrStreetType(String delAddrStreetType) {
		this.delAddrStreetType = delAddrStreetType;
	}

	@Column(name = "DEL_ADDR_CITY")
	public String getDelAddrCity() {
		return this.delAddrCity;
	}

	public void setDelAddrCity(String delAddrCity) {
		this.delAddrCity = delAddrCity;
	}

	@Column(name = "DEL_ADDR_STATE")
	public String getDelAddrState() {
		return this.delAddrState;
	}

	public void setDelAddrState(String delAddrState) {
		this.delAddrState = delAddrState;
	}

	@Column(name = "DEL_ADDR_POSTCODE")
	public String getDelAddrPostcode() {
		return this.delAddrPostcode;
	}

	public void setDelAddrPostcode(String delAddrPostcode) {
		this.delAddrPostcode = delAddrPostcode;
	}

	@Column(name = "SAP_DELIVERY")
	public String getSapDelivery() {
		return this.sapDelivery;
	}

	public void setSapDelivery(String sapDelivery) {
		this.sapDelivery = sapDelivery;
	}

	@Column(name = "HANDSET_SAP_DELIVERY")
	public String getHandsetSapDelivery() {
		return this.handsetSapDelivery;
	}

	public void setHandsetSapDelivery(String handsetSapDelivery) {
		this.handsetSapDelivery = handsetSapDelivery;
	}

	
	@Transient
	public String getValue(String propertyName) throws SecurityException,
		NoSuchFieldException, IllegalArgumentException, IllegalAccessException {
		Class<? extends OpomData> thisClass  = this.getClass();
		Field field =  thisClass.getDeclaredField(propertyName);
		field.setAccessible(true);
		String fieldValue = (String) field.get(this);
		return fieldValue;
	}
}
