package com.optus.supercal.entity;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.validation.constraints.NotNull;

import org.codehaus.jackson.annotate.JsonIgnore;
import org.hibernate.validator.constraints.Length;

/**
 * RatePlanFieldValue generated by hbm2java
 */
@Entity
@Table(name = "RATE_PLAN_FIELD_VALUE", catalog = "supercal")
public class RatePlanFieldValue implements java.io.Serializable, 
	Comparable<RatePlanFieldValue> {

	private static final long serialVersionUID = 3210866980619574546L;
	private Integer id;
	private RatePlanFamilyFieldConfig ratePlanFamilyFieldConfig;
	private RatePlan ratePlan;
	private String ratePlanFieldValue;

	public RatePlanFieldValue() {
	}

	public RatePlanFieldValue(
			RatePlanFamilyFieldConfig ratePlanFamilyFieldConfig,
			RatePlan ratePlan, String ratePlanFieldValue) {
		this.ratePlanFamilyFieldConfig = ratePlanFamilyFieldConfig;
		this.ratePlan = ratePlan;
		this.ratePlanFieldValue = ratePlanFieldValue;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "ID", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@JsonIgnore
	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "RATE_PLAN_FAMILY_FIELD_CONFIG_ID", nullable = false)
	@NotNull
	public RatePlanFamilyFieldConfig getRatePlanFamilyFieldConfig() {
		return this.ratePlanFamilyFieldConfig;
	}

	public void setRatePlanFamilyFieldConfig(
			RatePlanFamilyFieldConfig ratePlanFamilyFieldConfig) {
		this.ratePlanFamilyFieldConfig = ratePlanFamilyFieldConfig;
	}

	@JsonIgnore
	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "RATE_PLAN_ID", nullable = false)
	@NotNull
	public RatePlan getRatePlan() {
		return this.ratePlan;
	}

	public void setRatePlan(RatePlan ratePlan) {
		this.ratePlan = ratePlan;
	}

	@Column(name = "RATE_PLAN_FIELD_VALUE", nullable = false, length = 2000)
	@NotNull
	@Length(max = 2000)
	public String getRatePlanFieldValue() {
		return this.ratePlanFieldValue;
	}

	public void setRatePlanFieldValue(String ratePlanFieldValue) {
		this.ratePlanFieldValue = ratePlanFieldValue;
	}

	@Override
	public int compareTo(RatePlanFieldValue o) {
		return ratePlanFamilyFieldConfig.getSequenceNo() 
				- o.getRatePlanFamilyFieldConfig().getSequenceNo();
	}


}
