package com.optus.supercal.entity;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.validation.constraints.NotNull;

import org.codehaus.jackson.annotate.JsonIgnore;


/**
 * RatePlanFamilyBoltOnFamilyConfig generated by hbm2java
 */
@Entity
@Table(name = "RATE_PLAN_FAMILY_BOLT_ON_FAMILY_CONFIG", catalog = "supercal")
public class RatePlanFamilyBoltOnFamilyConfig implements java.io.Serializable,
	Comparable<RatePlanFamilyBoltOnFamilyConfig> {

	private static final long serialVersionUID = -3001042766155451571L;
	private Integer id;
	private RatePlanFamily ratePlanFamily;
	private BoltOnFamily boltOnFamily;
	private int sequenceNo;

	public RatePlanFamilyBoltOnFamilyConfig() {
	}

	public RatePlanFamilyBoltOnFamilyConfig(RatePlanFamily ratePlanFamily,
			BoltOnFamily boltOnFamily, int sequenceNo) {
		this.ratePlanFamily = ratePlanFamily;
		this.boltOnFamily = boltOnFamily;
		this.sequenceNo = sequenceNo;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "ID", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@JsonIgnore
	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "RATE_PLAN_FAMILY_ID", nullable = false)
	@NotNull
	public RatePlanFamily getRatePlanFamily() {
		return this.ratePlanFamily;
	}

	public void setRatePlanFamily(RatePlanFamily ratePlanFamily) {
		this.ratePlanFamily = ratePlanFamily;
	}

	@JsonIgnore
	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "BOLT_ON_FAMILY_ID", nullable = false)
	@NotNull
	public BoltOnFamily getBoltOnFamily() {
		return this.boltOnFamily;
	}

	public void setBoltOnFamily(BoltOnFamily boltOnFamily) {
		this.boltOnFamily = boltOnFamily;
	}

	@Column(name = "SEQUENCE_NO", nullable = false)
	public int getSequenceNo() {
		return this.sequenceNo;
	}

	public void setSequenceNo(int sequenceNo) {
		this.sequenceNo = sequenceNo;
	}

	@Override
	public int compareTo(RatePlanFamilyBoltOnFamilyConfig o) {
		return sequenceNo - o.sequenceNo;
	}

}
