package com.optus.supercal.entity;

import static javax.persistence.GenerationType.IDENTITY;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.validation.constraints.NotNull;

import org.codehaus.jackson.annotate.JsonIgnore;
import org.hibernate.validator.constraints.Length;


/**
 * RatePlanField generated by hbm2java
 */
@Entity
@Table(name = "RATE_PLAN_FIELD", catalog = "supercal")
public class RatePlanField implements java.io.Serializable {

	private static final long serialVersionUID = 2760329996235658936L;
	private Integer id;
	private String fieldName;
	private String fieldType;
	private char showInEmail;
	private Set<RatePlanFamilyFieldConfig> ratePlanFamilyFieldConfigs 
		= new HashSet<RatePlanFamilyFieldConfig>(0);

	public RatePlanField() {
	}

	public RatePlanField(String fieldName, String fieldType, char showInEmail) {
		this.fieldName = fieldName;
		this.fieldType = fieldType;
		this.showInEmail = showInEmail;
	}
	public RatePlanField(String fieldName, String fieldType, char showInEmail,
			Set<RatePlanFamilyFieldConfig> ratePlanFamilyFieldConfigs) {
		this.fieldName = fieldName;
		this.fieldType = fieldType;
		this.showInEmail = showInEmail;
		this.ratePlanFamilyFieldConfigs = ratePlanFamilyFieldConfigs;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "ID", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "FIELD_NAME", nullable = false, length = 100)
	@NotNull
	@Length(max = 100)
	public String getFieldName() {
		return this.fieldName;
	}

	public void setFieldName(String fieldName) {
		this.fieldName = fieldName;
	}

	@Column(name = "FIELD_TYPE", nullable = false, length = 8)
	@NotNull
	@Length(max = 8)
	public String getFieldType() {
		return this.fieldType;
	}

	public void setFieldType(String fieldType) {
		this.fieldType = fieldType;
	}

	@Column(name = "SHOW_IN_EMAIL", nullable = false, length = 1)
	public char getShowInEmail() {
		return this.showInEmail;
	}

	public void setShowInEmail(char showInEmail) {
		this.showInEmail = showInEmail;
	}

	@JsonIgnore
	@OneToMany(fetch = FetchType.EAGER, mappedBy = "ratePlanField")
	public Set<RatePlanFamilyFieldConfig> getRatePlanFamilyFieldConfigs() {
		return this.ratePlanFamilyFieldConfigs;
	}

	public void setRatePlanFamilyFieldConfigs(
			Set<RatePlanFamilyFieldConfig> ratePlanFamilyFieldConfigs) {
		this.ratePlanFamilyFieldConfigs = ratePlanFamilyFieldConfigs;
	}

}
