package com.optus.supercal.entity;

import static javax.persistence.GenerationType.IDENTITY;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.OrderBy;
import javax.persistence.Table;
import javax.persistence.Transient;
import javax.validation.constraints.NotNull;

import org.codehaus.jackson.annotate.JsonIgnore;
import org.hibernate.annotations.Cascade;
import org.hibernate.validator.constraints.Length;

/**
 * RatePlanFamily generated by hbm2java
 */
@Entity
@Table(name = "RATE_PLAN_FAMILY", catalog = "supercal")
public class RatePlanFamily implements java.io.Serializable {

	private static final long serialVersionUID = 5975470256481547486L;
	private Integer id;
	private String ratePlanFamilyName;
	private String status;
	private Set<RatePlanFamilyBoltOnFamilyConfig> ratePlanFamilyBoltOnFamilyConfigs
		= new HashSet<RatePlanFamilyBoltOnFamilyConfig>(0);
	private Set<ProductRatePlanFamily> productRatePlanFamilies
		= new HashSet<ProductRatePlanFamily>(0);
	private Set<RatePlanFamilyFieldConfig> ratePlanFamilyFieldConfigs
		= new HashSet<RatePlanFamilyFieldConfig>(0);

	public RatePlanFamily() {
	}

	public RatePlanFamily(String ratePlanFamilyName, String status) {
		this.ratePlanFamilyName = ratePlanFamilyName;
		this.status = status;
	}
	public RatePlanFamily(
			String ratePlanFamilyName,
			String status,
			Set<RatePlanFamilyBoltOnFamilyConfig> ratePlanFamilyBoltOnFamilyConfigs,
			Set<ProductRatePlanFamily> productRatePlanFamilies,
			Set<RatePlanFamilyFieldConfig> ratePlanFamilyFieldConfigs) {
		this.ratePlanFamilyName = ratePlanFamilyName;
		this.status = status;
		this.ratePlanFamilyBoltOnFamilyConfigs = ratePlanFamilyBoltOnFamilyConfigs;
		this.productRatePlanFamilies = productRatePlanFamilies;
		this.ratePlanFamilyFieldConfigs = ratePlanFamilyFieldConfigs;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "ID", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "RATE_PLAN_FAMILY_NAME", nullable = false, length = 150)
	@NotNull
	@Length(max = 150)
	public String getRatePlanFamilyName() {
		return this.ratePlanFamilyName;
	}

	public void setRatePlanFamilyName(String ratePlanFamilyName) {
		this.ratePlanFamilyName = ratePlanFamilyName;
	}

	@Column(name = "STATUS", nullable = false, length = 8)
	@NotNull
	@Length(max = 8)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	@JsonIgnore
	@OneToMany(fetch = FetchType.EAGER, cascade=CascadeType.ALL,
			mappedBy = "ratePlanFamily")
	@OrderBy("sequenceNo asc")
	public Set<RatePlanFamilyBoltOnFamilyConfig> getRatePlanFamilyBoltOnFamilyConfigs() {
		return this.ratePlanFamilyBoltOnFamilyConfigs;
	}

	public void setRatePlanFamilyBoltOnFamilyConfigs(
			Set<RatePlanFamilyBoltOnFamilyConfig> ratePlanFamilyBoltOnFamilyConfigs) {
		this.ratePlanFamilyBoltOnFamilyConfigs = ratePlanFamilyBoltOnFamilyConfigs;
	}

	@JsonIgnore
	@OneToMany(fetch = FetchType.EAGER, cascade=CascadeType.ALL,
			mappedBy = "ratePlanFamily")
	public Set<ProductRatePlanFamily> getProductRatePlanFamilies() {
		return this.productRatePlanFamilies;
	}

	public void setProductRatePlanFamilies(
			Set<ProductRatePlanFamily> productRatePlanFamilies) {
		this.productRatePlanFamilies = productRatePlanFamilies;
	}

	@JsonIgnore
	@OneToMany(fetch = FetchType.EAGER, cascade=CascadeType.ALL,
			mappedBy = "ratePlanFamily", orphanRemoval=true)
	/*@Cascade(value={org.hibernate.annotations.CascadeType.ALL, 
			org.hibernate.annotations.CascadeType.DELETE_ORPHAN})*/
	@OrderBy("sequenceNo asc")
	public Set<RatePlanFamilyFieldConfig> getRatePlanFamilyFieldConfigs() {
		return this.ratePlanFamilyFieldConfigs;
	}

	public void setRatePlanFamilyFieldConfigs(
			Set<RatePlanFamilyFieldConfig> ratePlanFamilyFieldConfigs) {
		this.ratePlanFamilyFieldConfigs = ratePlanFamilyFieldConfigs;
	}
	
	@Transient
	public Product getProduct() {
		return getProductRatePlanFamilies().iterator()
				.next().getProduct();
	}
}
